apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: frontend
  labels:
    app: frontend
    group: devops
spec:
  # modify replicas according to your case
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: ashutoshshukla/finalproj-frontend:v1
        imagePullPolicy: Always
        ports:
          - { containerPort: 4200,  protocol: TCP }
        resources:
          requests:
            memory: "524Mi"
            cpu: "100m"
          limits:
            memory: "1024Mi"
            cpu: "2"